// Nuno's role weights (Stats + Att hybrid).
export type WeightedItem = { name: string; pct: number; note?: string };
export type NunoRole = {
  emoji: string;
  name: string;
  subtitle?: string;
  attributes: WeightedItem[];
  metrics: WeightedItem[];
  note?: string;
};

export const NUNO_ROLES: NunoRole[] = [
  {
    emoji: "🧠",
    name: "Central Defensivo",
    subtitle: "CB — Posicional / inteligente",
    attributes: [
      { name: "Positioning", pct: 22 },
      { name: "Anticipation", pct: 20 },
      { name: "Tackling", pct: 15 },
      { name: "Jumping Reach", pct: 12 },
      { name: "Strength", pct: 10 },
      { name: "Concentration", pct: 10 },
      { name: "Heading", pct: 6 },
      { name: "Pace", pct: 5 },
    ],
    metrics: [
      { name: "Interceptions", pct: 30 },
      { name: "Clearances", pct: 20 },
      { name: "Tackles Completed", pct: 20 },
      { name: "Key Headers Won", pct: 15 },
      { name: "Blocks", pct: 15 },
    ],
    note: "Central bom aqui não é o que 'tackla mais', é o que intercepta mais.",
  },
  {
    emoji: "🧱",
    name: "Central Defensivo",
    subtitle: "Stopper agressivo",
    attributes: [
      { name: "Tackling", pct: 25 },
      { name: "Strength", pct: 18 },
      { name: "Bravery", pct: 15 },
      { name: "Aggression", pct: 12 },
      { name: "Jumping Reach", pct: 10 },
      { name: "Positioning", pct: 10 },
      { name: "Concentration", pct: 10 },
    ],
    metrics: [
      { name: "Tackles Completed", pct: 35 },
      { name: "Blocks", pct: 25 },
      { name: "Clearances", pct: 20 },
      { name: "Fouls Committed", pct: 10, note: "controlo" },
      { name: "Headers Won", pct: 10 },
    ],
  },
  {
    emoji: "🧠",
    name: "Médio Defensivo",
    subtitle: "Anchor / DM",
    attributes: [
      { name: "Positioning", pct: 25 },
      { name: "Anticipation", pct: 20 },
      { name: "Decisions", pct: 15 },
      { name: "Work Rate", pct: 12 },
      { name: "Tackling", pct: 10 },
      { name: "Passing", pct: 10 },
      { name: "Stamina", pct: 8 },
    ],
    metrics: [
      { name: "Interceptions", pct: 35 },
      { name: "Press Completed", pct: 20 },
      { name: "Passes Completed", pct: 20 },
      { name: "Tackles Completed", pct: 15 },
      { name: "Distance Covered", pct: 10 },
    ],
  },
  {
    emoji: "⚙️",
    name: "Box-to-Box",
    attributes: [
      { name: "Stamina", pct: 20 },
      { name: "Work Rate", pct: 20 },
      { name: "Decisions", pct: 15 },
      { name: "Passing", pct: 10 },
      { name: "Off the Ball", pct: 10 },
      { name: "Tackling", pct: 10 },
      { name: "Pace", pct: 10 },
      { name: "Vision", pct: 5 },
    ],
    metrics: [
      { name: "Distance Covered", pct: 30 },
      { name: "Sprints", pct: 20 },
      { name: "Passes Completed", pct: 20 },
      { name: "Press Attempts", pct: 15 },
      { name: "Tackles Completed", pct: 15 },
    ],
  },
  {
    emoji: "🎨",
    name: "Médio Criativo",
    subtitle: "Playmaker",
    attributes: [
      { name: "Vision", pct: 25 },
      { name: "Passing", pct: 25 },
      { name: "Decisions", pct: 20 },
      { name: "Technique", pct: 10 },
      { name: "First Touch", pct: 10 },
      { name: "Flair", pct: 5 },
      { name: "Off the Ball", pct: 5 },
    ],
    metrics: [
      { name: "Key Passes", pct: 40 },
      { name: "Forward Passes", pct: 25 },
      { name: "Passes Completed", pct: 20 },
      { name: "Crosses Completed", pct: 15, note: "se aplicável" },
    ],
  },
  {
    emoji: "🪄",
    name: "Mezzala",
    attributes: [
      { name: "Vision", pct: 20 },
      { name: "Passing", pct: 15 },
      { name: "Off the Ball", pct: 15 },
      { name: "Decisions", pct: 15 },
      { name: "Dribbling", pct: 10 },
      { name: "Work Rate", pct: 10 },
      { name: "Technique", pct: 10 },
      { name: "Stamina", pct: 5 },
    ],
    metrics: [
      { name: "Key Passes", pct: 30 },
      { name: "Dribbles", pct: 25 },
      { name: "Passes Completed", pct: 20 },
      { name: "Distance Covered", pct: 15 },
      { name: "Forward Passes", pct: 10 },
    ],
  },
  {
    emoji: "🪽",
    name: "Extremo Clássico",
    subtitle: "Winger",
    attributes: [
      { name: "Crossing", pct: 25 },
      { name: "Pace", pct: 20 },
      { name: "Acceleration", pct: 15 },
      { name: "Work Rate", pct: 10 },
      { name: "Dribbling", pct: 10 },
      { name: "Stamina", pct: 10 },
      { name: "Vision", pct: 5 },
      { name: "Technique", pct: 5 },
    ],
    metrics: [
      { name: "Cross Attempts", pct: 30 },
      { name: "Crosses Completed", pct: 25 },
      { name: "Dribbles", pct: 20 },
      { name: "Sprints", pct: 15 },
      { name: "Distance Covered", pct: 10 },
    ],
  },
  {
    emoji: "🪄",
    name: "Extremo Invertido",
    subtitle: "Inside Forward",
    attributes: [
      { name: "Dribbling", pct: 20 },
      { name: "Acceleration", pct: 15 },
      { name: "Pace", pct: 15 },
      { name: "Decisions", pct: 15 },
      { name: "Finishing", pct: 10 },
      { name: "Technique", pct: 10 },
      { name: "Off the Ball", pct: 10 },
      { name: "Flair", pct: 5 },
    ],
    metrics: [
      { name: "Dribbles", pct: 30 },
      { name: "Key Passes", pct: 20 },
      { name: "Shots on Target", pct: 20 },
      { name: "Sprints", pct: 15 },
      { name: "Passes Completed", pct: 15 },
    ],
  },
  {
    emoji: "🎯",
    name: "Avançado",
    subtitle: "Pressing Forward",
    attributes: [
      { name: "Work Rate", pct: 20 },
      { name: "Stamina", pct: 15 },
      { name: "Off the Ball", pct: 15 },
      { name: "Aggression", pct: 10 },
      { name: "Finishing", pct: 10 },
      { name: "Strength", pct: 10 },
      { name: "Pace", pct: 10 },
      { name: "Decisions", pct: 10 },
    ],
    metrics: [
      { name: "Press Attempts", pct: 30 },
      { name: "Sprints", pct: 20 },
      { name: "Shots", pct: 20 },
      { name: "Distance Covered", pct: 15 },
      { name: "Tackles Completed", pct: 15 },
    ],
  },
  {
    emoji: "🎯",
    name: "Avançado Finalizador",
    subtitle: "Poacher",
    attributes: [
      { name: "Finishing", pct: 30 },
      { name: "Off the Ball", pct: 20 },
      { name: "Composure", pct: 15 },
      { name: "Acceleration", pct: 10 },
      { name: "Pace", pct: 10 },
      { name: "Technique", pct: 10 },
      { name: "Decisions", pct: 5 },
    ],
    metrics: [
      { name: "Goals", pct: 40 },
      { name: "Shots on Target", pct: 30 },
      { name: "Key Shots", pct: 15 },
      { name: "Touches in Box", pct: 15 },
    ],
  },
  {
    emoji: "🔁",
    name: "Lateral",
    subtitle: "Fullback equilibrado",
    attributes: [
      { name: "Stamina", pct: 20 },
      { name: "Work Rate", pct: 20 },
      { name: "Crossing", pct: 15 },
      { name: "Positioning", pct: 15 },
      { name: "Tackling", pct: 10 },
      { name: "Pace", pct: 10 },
      { name: "Acceleration", pct: 5 },
      { name: "Decisions", pct: 5 },
    ],
    metrics: [
      { name: "Distance Covered", pct: 30 },
      { name: "Cross Attempts", pct: 20 },
      { name: "Tackles Completed", pct: 20 },
      { name: "Sprints", pct: 15 },
      { name: "Crosses Completed", pct: 15 },
    ],
  },
  {
    emoji: "🔁",
    name: "Lateral Invertido",
    attributes: [
      { name: "Passing", pct: 20 },
      { name: "Decisions", pct: 20 },
      { name: "Positioning", pct: 15 },
      { name: "Vision", pct: 15 },
      { name: "Technique", pct: 10 },
      { name: "Work Rate", pct: 10 },
      { name: "First Touch", pct: 10 },
    ],
    metrics: [
      { name: "Passes Completed", pct: 30 },
      { name: "Forward Passes", pct: 25 },
      { name: "Key Passes", pct: 20 },
      { name: "Press Completed", pct: 15 },
      { name: "Distance Covered", pct: 10 },
    ],
  },
];
