/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsAttRouteImport } from './routes/stats-att'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AttRouteImport } from './routes/att'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as StatsWeightsRouteImport } from './routes/stats.weights'
import { Route as StatsTableRouteImport } from './routes/stats.table'

const StatsAttRoute = StatsAttRouteImport.update({
  id: '/stats-att',
  path: '/stats-att',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AttRoute = AttRouteImport.update({
  id: '/att',
  path: '/att',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsWeightsRoute = StatsWeightsRouteImport.update({
  id: '/stats/weights',
  path: '/stats/weights',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsTableRoute = StatsTableRouteImport.update({
  id: '/stats/table',
  path: '/stats/table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/att': typeof AttRoute
  '/dashboard': typeof DashboardRoute
  '/stats-att': typeof StatsAttRoute
  '/stats/table': typeof StatsTableRoute
  '/stats/weights': typeof StatsWeightsRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/att': typeof AttRoute
  '/dashboard': typeof DashboardRoute
  '/stats-att': typeof StatsAttRoute
  '/stats/table': typeof StatsTableRoute
  '/stats/weights': typeof StatsWeightsRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/att': typeof AttRoute
  '/dashboard': typeof DashboardRoute
  '/stats-att': typeof StatsAttRoute
  '/stats/table': typeof StatsTableRoute
  '/stats/weights': typeof StatsWeightsRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/att'
    | '/dashboard'
    | '/stats-att'
    | '/stats/table'
    | '/stats/weights'
    | '/stats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/att'
    | '/dashboard'
    | '/stats-att'
    | '/stats/table'
    | '/stats/weights'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/att'
    | '/dashboard'
    | '/stats-att'
    | '/stats/table'
    | '/stats/weights'
    | '/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttRoute: typeof AttRoute
  DashboardRoute: typeof DashboardRoute
  StatsAttRoute: typeof StatsAttRoute
  StatsTableRoute: typeof StatsTableRoute
  StatsWeightsRoute: typeof StatsWeightsRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats-att': {
      id: '/stats-att'
      path: '/stats-att'
      fullPath: '/stats-att'
      preLoaderRoute: typeof StatsAttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/att': {
      id: '/att'
      path: '/att'
      fullPath: '/att'
      preLoaderRoute: typeof AttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/weights': {
      id: '/stats/weights'
      path: '/stats/weights'
      fullPath: '/stats/weights'
      preLoaderRoute: typeof StatsWeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/table': {
      id: '/stats/table'
      path: '/stats/table'
      fullPath: '/stats/table'
      preLoaderRoute: typeof StatsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttRoute: AttRoute,
  DashboardRoute: DashboardRoute,
  StatsAttRoute: StatsAttRoute,
  StatsTableRoute: StatsTableRoute,
  StatsWeightsRoute: StatsWeightsRoute,
  StatsIndexRoute: StatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
