/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as StatsAttIndexRouteImport } from './routes/stats-att.index'
import { Route as AttIndexRouteImport } from './routes/att.index'
import { Route as StatsWeightsRouteImport } from './routes/stats.weights'
import { Route as StatsTableRouteImport } from './routes/stats.table'
import { Route as StatsAttWeightsRouteImport } from './routes/stats-att.weights'
import { Route as StatsAttTableRouteImport } from './routes/stats-att.table'
import { Route as AttWeightsRouteImport } from './routes/att.weights'
import { Route as AttTableRouteImport } from './routes/att.table'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsAttIndexRoute = StatsAttIndexRouteImport.update({
  id: '/stats-att/',
  path: '/stats-att/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttIndexRoute = AttIndexRouteImport.update({
  id: '/att/',
  path: '/att/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsWeightsRoute = StatsWeightsRouteImport.update({
  id: '/stats/weights',
  path: '/stats/weights',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsTableRoute = StatsTableRouteImport.update({
  id: '/stats/table',
  path: '/stats/table',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsAttWeightsRoute = StatsAttWeightsRouteImport.update({
  id: '/stats-att/weights',
  path: '/stats-att/weights',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsAttTableRoute = StatsAttTableRouteImport.update({
  id: '/stats-att/table',
  path: '/stats-att/table',
  getParentRoute: () => rootRouteImport,
} as any)
const AttWeightsRoute = AttWeightsRouteImport.update({
  id: '/att/weights',
  path: '/att/weights',
  getParentRoute: () => rootRouteImport,
} as any)
const AttTableRoute = AttTableRouteImport.update({
  id: '/att/table',
  path: '/att/table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/att/table': typeof AttTableRoute
  '/att/weights': typeof AttWeightsRoute
  '/stats-att/table': typeof StatsAttTableRoute
  '/stats-att/weights': typeof StatsAttWeightsRoute
  '/stats/table': typeof StatsTableRoute
  '/stats/weights': typeof StatsWeightsRoute
  '/att/': typeof AttIndexRoute
  '/stats-att/': typeof StatsAttIndexRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/att/table': typeof AttTableRoute
  '/att/weights': typeof AttWeightsRoute
  '/stats-att/table': typeof StatsAttTableRoute
  '/stats-att/weights': typeof StatsAttWeightsRoute
  '/stats/table': typeof StatsTableRoute
  '/stats/weights': typeof StatsWeightsRoute
  '/att': typeof AttIndexRoute
  '/stats-att': typeof StatsAttIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/att/table': typeof AttTableRoute
  '/att/weights': typeof AttWeightsRoute
  '/stats-att/table': typeof StatsAttTableRoute
  '/stats-att/weights': typeof StatsAttWeightsRoute
  '/stats/table': typeof StatsTableRoute
  '/stats/weights': typeof StatsWeightsRoute
  '/att/': typeof AttIndexRoute
  '/stats-att/': typeof StatsAttIndexRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/att/table'
    | '/att/weights'
    | '/stats-att/table'
    | '/stats-att/weights'
    | '/stats/table'
    | '/stats/weights'
    | '/att/'
    | '/stats-att/'
    | '/stats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/att/table'
    | '/att/weights'
    | '/stats-att/table'
    | '/stats-att/weights'
    | '/stats/table'
    | '/stats/weights'
    | '/att'
    | '/stats-att'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/att/table'
    | '/att/weights'
    | '/stats-att/table'
    | '/stats-att/weights'
    | '/stats/table'
    | '/stats/weights'
    | '/att/'
    | '/stats-att/'
    | '/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AttTableRoute: typeof AttTableRoute
  AttWeightsRoute: typeof AttWeightsRoute
  StatsAttTableRoute: typeof StatsAttTableRoute
  StatsAttWeightsRoute: typeof StatsAttWeightsRoute
  StatsTableRoute: typeof StatsTableRoute
  StatsWeightsRoute: typeof StatsWeightsRoute
  AttIndexRoute: typeof AttIndexRoute
  StatsAttIndexRoute: typeof StatsAttIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats-att/': {
      id: '/stats-att/'
      path: '/stats-att'
      fullPath: '/stats-att/'
      preLoaderRoute: typeof StatsAttIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/att/': {
      id: '/att/'
      path: '/att'
      fullPath: '/att/'
      preLoaderRoute: typeof AttIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/weights': {
      id: '/stats/weights'
      path: '/stats/weights'
      fullPath: '/stats/weights'
      preLoaderRoute: typeof StatsWeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/table': {
      id: '/stats/table'
      path: '/stats/table'
      fullPath: '/stats/table'
      preLoaderRoute: typeof StatsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats-att/weights': {
      id: '/stats-att/weights'
      path: '/stats-att/weights'
      fullPath: '/stats-att/weights'
      preLoaderRoute: typeof StatsAttWeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats-att/table': {
      id: '/stats-att/table'
      path: '/stats-att/table'
      fullPath: '/stats-att/table'
      preLoaderRoute: typeof StatsAttTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/att/weights': {
      id: '/att/weights'
      path: '/att/weights'
      fullPath: '/att/weights'
      preLoaderRoute: typeof AttWeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/att/table': {
      id: '/att/table'
      path: '/att/table'
      fullPath: '/att/table'
      preLoaderRoute: typeof AttTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AttTableRoute: AttTableRoute,
  AttWeightsRoute: AttWeightsRoute,
  StatsAttTableRoute: StatsAttTableRoute,
  StatsAttWeightsRoute: StatsAttWeightsRoute,
  StatsTableRoute: StatsTableRoute,
  StatsWeightsRoute: StatsWeightsRoute,
  AttIndexRoute: AttIndexRoute,
  StatsAttIndexRoute: StatsAttIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
